#if !defined(__SG_INTERNAL_H__)
#define __SG_INTERNAL_H__

#include "sg_public.h"
#include "common.h"
#include "usignal.h"
#include "sys_func.h"
#include "gpenv.h"
#include "sgp_ctx.h"
#include "sgt_ctx.h"
#include "sgc_ctx.h"
#include "sg_manager.h"
#include "sg_xmlcfg.h"
#include "sg_config.h"
#include "sg_pte.h"
#include "sg_nte.h"
#include "sg_rte.h"
#include "sg_sgte.h"
#include "sg_ste.h"
#include "sg_scte.h"
#include "sg_qte.h"
#include "sg_proc.h"
#include "sg_lock.h"
#include "sg_ipc.h"
#include "sg_options.h"
#include "sg_viable.h"
#include "sg_agent.h"
#include "sg_rpc.h"
#include "sg_switch.h"
#include "sg_svcdsp.h"
#include "sg_svr.h"
#include "sg_handle.h"
#include "sg_meta.h"
#include "bs_struct.h"
#include "file_rpc.h"
#include "alive_rpc.h"

#endif

