/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ailk.monitor;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OperateType implements org.apache.thrift.TEnum {
  Server(1),
  ServerGroup(2),
  Machine(3),
  All(4);

  private final int value;

  private OperateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OperateType findByValue(int value) { 
    switch (value) {
      case 1:
        return Server;
      case 2:
        return ServerGroup;
      case 3:
        return Machine;
      case 4:
        return All;
      default:
        return null;
    }
  }
}
