/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ailk.monitor;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class QueueState implements org.apache.thrift.TBase<QueueState, QueueState._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueueState");

  private static final org.apache.thrift.protocol.TField SGID_FIELD_DESC = new org.apache.thrift.protocol.TField("sgid", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SADDR_FIELD_DESC = new org.apache.thrift.protocol.TField("saddr", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TOTNQUEUED_FIELD_DESC = new org.apache.thrift.protocol.TField("totnqueued", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField NQUEUED_FIELD_DESC = new org.apache.thrift.protocol.TField("nqueued", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField TOTWKQUEUED_FIELD_DESC = new org.apache.thrift.protocol.TField("totwkqueued", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField WKQUEUED_FIELD_DESC = new org.apache.thrift.protocol.TField("wkqueued", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField SVRCNT_FIELD_DESC = new org.apache.thrift.protocol.TField("svrcnt", org.apache.thrift.protocol.TType.I32, (short)8);
  private static final org.apache.thrift.protocol.TField SPAWN_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("spawn_state", org.apache.thrift.protocol.TType.I32, (short)9);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueueStateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueueStateTupleSchemeFactory());
  }

  public long sgid; // required
  public String saddr; // required
  public int totnqueued; // required
  public int nqueued; // required
  public long totwkqueued; // required
  public long wkqueued; // required
  public int status; // required
  public int svrcnt; // required
  public int spawn_state; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SGID((short)1, "sgid"),
    SADDR((short)2, "saddr"),
    TOTNQUEUED((short)3, "totnqueued"),
    NQUEUED((short)4, "nqueued"),
    TOTWKQUEUED((short)5, "totwkqueued"),
    WKQUEUED((short)6, "wkqueued"),
    STATUS((short)7, "status"),
    SVRCNT((short)8, "svrcnt"),
    SPAWN_STATE((short)9, "spawn_state");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SGID
          return SGID;
        case 2: // SADDR
          return SADDR;
        case 3: // TOTNQUEUED
          return TOTNQUEUED;
        case 4: // NQUEUED
          return NQUEUED;
        case 5: // TOTWKQUEUED
          return TOTWKQUEUED;
        case 6: // WKQUEUED
          return WKQUEUED;
        case 7: // STATUS
          return STATUS;
        case 8: // SVRCNT
          return SVRCNT;
        case 9: // SPAWN_STATE
          return SPAWN_STATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SGID_ISSET_ID = 0;
  private static final int __TOTNQUEUED_ISSET_ID = 1;
  private static final int __NQUEUED_ISSET_ID = 2;
  private static final int __TOTWKQUEUED_ISSET_ID = 3;
  private static final int __WKQUEUED_ISSET_ID = 4;
  private static final int __STATUS_ISSET_ID = 5;
  private static final int __SVRCNT_ISSET_ID = 6;
  private static final int __SPAWN_STATE_ISSET_ID = 7;
  private BitSet __isset_bit_vector = new BitSet(8);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SGID, new org.apache.thrift.meta_data.FieldMetaData("sgid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SADDR, new org.apache.thrift.meta_data.FieldMetaData("saddr", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TOTNQUEUED, new org.apache.thrift.meta_data.FieldMetaData("totnqueued", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NQUEUED, new org.apache.thrift.meta_data.FieldMetaData("nqueued", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TOTWKQUEUED, new org.apache.thrift.meta_data.FieldMetaData("totwkqueued", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.WKQUEUED, new org.apache.thrift.meta_data.FieldMetaData("wkqueued", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SVRCNT, new org.apache.thrift.meta_data.FieldMetaData("svrcnt", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SPAWN_STATE, new org.apache.thrift.meta_data.FieldMetaData("spawn_state", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueueState.class, metaDataMap);
  }

  public QueueState() {
  }

  public QueueState(
    long sgid,
    String saddr,
    int totnqueued,
    int nqueued,
    long totwkqueued,
    long wkqueued,
    int status,
    int svrcnt,
    int spawn_state)
  {
    this();
    this.sgid = sgid;
    setSgidIsSet(true);
    this.saddr = saddr;
    this.totnqueued = totnqueued;
    setTotnqueuedIsSet(true);
    this.nqueued = nqueued;
    setNqueuedIsSet(true);
    this.totwkqueued = totwkqueued;
    setTotwkqueuedIsSet(true);
    this.wkqueued = wkqueued;
    setWkqueuedIsSet(true);
    this.status = status;
    setStatusIsSet(true);
    this.svrcnt = svrcnt;
    setSvrcntIsSet(true);
    this.spawn_state = spawn_state;
    setSpawn_stateIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueueState(QueueState other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.sgid = other.sgid;
    if (other.isSetSaddr()) {
      this.saddr = other.saddr;
    }
    this.totnqueued = other.totnqueued;
    this.nqueued = other.nqueued;
    this.totwkqueued = other.totwkqueued;
    this.wkqueued = other.wkqueued;
    this.status = other.status;
    this.svrcnt = other.svrcnt;
    this.spawn_state = other.spawn_state;
  }

  public QueueState deepCopy() {
    return new QueueState(this);
  }

  @Override
  public void clear() {
    setSgidIsSet(false);
    this.sgid = 0;
    this.saddr = null;
    setTotnqueuedIsSet(false);
    this.totnqueued = 0;
    setNqueuedIsSet(false);
    this.nqueued = 0;
    setTotwkqueuedIsSet(false);
    this.totwkqueued = 0;
    setWkqueuedIsSet(false);
    this.wkqueued = 0;
    setStatusIsSet(false);
    this.status = 0;
    setSvrcntIsSet(false);
    this.svrcnt = 0;
    setSpawn_stateIsSet(false);
    this.spawn_state = 0;
  }

  public long getSgid() {
    return this.sgid;
  }

  public QueueState setSgid(long sgid) {
    this.sgid = sgid;
    setSgidIsSet(true);
    return this;
  }

  public void unsetSgid() {
    __isset_bit_vector.clear(__SGID_ISSET_ID);
  }

  /** Returns true if field sgid is set (has been assigned a value) and false otherwise */
  public boolean isSetSgid() {
    return __isset_bit_vector.get(__SGID_ISSET_ID);
  }

  public void setSgidIsSet(boolean value) {
    __isset_bit_vector.set(__SGID_ISSET_ID, value);
  }

  public String getSaddr() {
    return this.saddr;
  }

  public QueueState setSaddr(String saddr) {
    this.saddr = saddr;
    return this;
  }

  public void unsetSaddr() {
    this.saddr = null;
  }

  /** Returns true if field saddr is set (has been assigned a value) and false otherwise */
  public boolean isSetSaddr() {
    return this.saddr != null;
  }

  public void setSaddrIsSet(boolean value) {
    if (!value) {
      this.saddr = null;
    }
  }

  public int getTotnqueued() {
    return this.totnqueued;
  }

  public QueueState setTotnqueued(int totnqueued) {
    this.totnqueued = totnqueued;
    setTotnqueuedIsSet(true);
    return this;
  }

  public void unsetTotnqueued() {
    __isset_bit_vector.clear(__TOTNQUEUED_ISSET_ID);
  }

  /** Returns true if field totnqueued is set (has been assigned a value) and false otherwise */
  public boolean isSetTotnqueued() {
    return __isset_bit_vector.get(__TOTNQUEUED_ISSET_ID);
  }

  public void setTotnqueuedIsSet(boolean value) {
    __isset_bit_vector.set(__TOTNQUEUED_ISSET_ID, value);
  }

  public int getNqueued() {
    return this.nqueued;
  }

  public QueueState setNqueued(int nqueued) {
    this.nqueued = nqueued;
    setNqueuedIsSet(true);
    return this;
  }

  public void unsetNqueued() {
    __isset_bit_vector.clear(__NQUEUED_ISSET_ID);
  }

  /** Returns true if field nqueued is set (has been assigned a value) and false otherwise */
  public boolean isSetNqueued() {
    return __isset_bit_vector.get(__NQUEUED_ISSET_ID);
  }

  public void setNqueuedIsSet(boolean value) {
    __isset_bit_vector.set(__NQUEUED_ISSET_ID, value);
  }

  public long getTotwkqueued() {
    return this.totwkqueued;
  }

  public QueueState setTotwkqueued(long totwkqueued) {
    this.totwkqueued = totwkqueued;
    setTotwkqueuedIsSet(true);
    return this;
  }

  public void unsetTotwkqueued() {
    __isset_bit_vector.clear(__TOTWKQUEUED_ISSET_ID);
  }

  /** Returns true if field totwkqueued is set (has been assigned a value) and false otherwise */
  public boolean isSetTotwkqueued() {
    return __isset_bit_vector.get(__TOTWKQUEUED_ISSET_ID);
  }

  public void setTotwkqueuedIsSet(boolean value) {
    __isset_bit_vector.set(__TOTWKQUEUED_ISSET_ID, value);
  }

  public long getWkqueued() {
    return this.wkqueued;
  }

  public QueueState setWkqueued(long wkqueued) {
    this.wkqueued = wkqueued;
    setWkqueuedIsSet(true);
    return this;
  }

  public void unsetWkqueued() {
    __isset_bit_vector.clear(__WKQUEUED_ISSET_ID);
  }

  /** Returns true if field wkqueued is set (has been assigned a value) and false otherwise */
  public boolean isSetWkqueued() {
    return __isset_bit_vector.get(__WKQUEUED_ISSET_ID);
  }

  public void setWkqueuedIsSet(boolean value) {
    __isset_bit_vector.set(__WKQUEUED_ISSET_ID, value);
  }

  public int getStatus() {
    return this.status;
  }

  public QueueState setStatus(int status) {
    this.status = status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bit_vector.clear(__STATUS_ISSET_ID);
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return __isset_bit_vector.get(__STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bit_vector.set(__STATUS_ISSET_ID, value);
  }

  public int getSvrcnt() {
    return this.svrcnt;
  }

  public QueueState setSvrcnt(int svrcnt) {
    this.svrcnt = svrcnt;
    setSvrcntIsSet(true);
    return this;
  }

  public void unsetSvrcnt() {
    __isset_bit_vector.clear(__SVRCNT_ISSET_ID);
  }

  /** Returns true if field svrcnt is set (has been assigned a value) and false otherwise */
  public boolean isSetSvrcnt() {
    return __isset_bit_vector.get(__SVRCNT_ISSET_ID);
  }

  public void setSvrcntIsSet(boolean value) {
    __isset_bit_vector.set(__SVRCNT_ISSET_ID, value);
  }

  public int getSpawn_state() {
    return this.spawn_state;
  }

  public QueueState setSpawn_state(int spawn_state) {
    this.spawn_state = spawn_state;
    setSpawn_stateIsSet(true);
    return this;
  }

  public void unsetSpawn_state() {
    __isset_bit_vector.clear(__SPAWN_STATE_ISSET_ID);
  }

  /** Returns true if field spawn_state is set (has been assigned a value) and false otherwise */
  public boolean isSetSpawn_state() {
    return __isset_bit_vector.get(__SPAWN_STATE_ISSET_ID);
  }

  public void setSpawn_stateIsSet(boolean value) {
    __isset_bit_vector.set(__SPAWN_STATE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SGID:
      if (value == null) {
        unsetSgid();
      } else {
        setSgid((Long)value);
      }
      break;

    case SADDR:
      if (value == null) {
        unsetSaddr();
      } else {
        setSaddr((String)value);
      }
      break;

    case TOTNQUEUED:
      if (value == null) {
        unsetTotnqueued();
      } else {
        setTotnqueued((Integer)value);
      }
      break;

    case NQUEUED:
      if (value == null) {
        unsetNqueued();
      } else {
        setNqueued((Integer)value);
      }
      break;

    case TOTWKQUEUED:
      if (value == null) {
        unsetTotwkqueued();
      } else {
        setTotwkqueued((Long)value);
      }
      break;

    case WKQUEUED:
      if (value == null) {
        unsetWkqueued();
      } else {
        setWkqueued((Long)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Integer)value);
      }
      break;

    case SVRCNT:
      if (value == null) {
        unsetSvrcnt();
      } else {
        setSvrcnt((Integer)value);
      }
      break;

    case SPAWN_STATE:
      if (value == null) {
        unsetSpawn_state();
      } else {
        setSpawn_state((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SGID:
      return Long.valueOf(getSgid());

    case SADDR:
      return getSaddr();

    case TOTNQUEUED:
      return Integer.valueOf(getTotnqueued());

    case NQUEUED:
      return Integer.valueOf(getNqueued());

    case TOTWKQUEUED:
      return Long.valueOf(getTotwkqueued());

    case WKQUEUED:
      return Long.valueOf(getWkqueued());

    case STATUS:
      return Integer.valueOf(getStatus());

    case SVRCNT:
      return Integer.valueOf(getSvrcnt());

    case SPAWN_STATE:
      return Integer.valueOf(getSpawn_state());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SGID:
      return isSetSgid();
    case SADDR:
      return isSetSaddr();
    case TOTNQUEUED:
      return isSetTotnqueued();
    case NQUEUED:
      return isSetNqueued();
    case TOTWKQUEUED:
      return isSetTotwkqueued();
    case WKQUEUED:
      return isSetWkqueued();
    case STATUS:
      return isSetStatus();
    case SVRCNT:
      return isSetSvrcnt();
    case SPAWN_STATE:
      return isSetSpawn_state();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueueState)
      return this.equals((QueueState)that);
    return false;
  }

  public boolean equals(QueueState that) {
    if (that == null)
      return false;

    boolean this_present_sgid = true;
    boolean that_present_sgid = true;
    if (this_present_sgid || that_present_sgid) {
      if (!(this_present_sgid && that_present_sgid))
        return false;
      if (this.sgid != that.sgid)
        return false;
    }

    boolean this_present_saddr = true && this.isSetSaddr();
    boolean that_present_saddr = true && that.isSetSaddr();
    if (this_present_saddr || that_present_saddr) {
      if (!(this_present_saddr && that_present_saddr))
        return false;
      if (!this.saddr.equals(that.saddr))
        return false;
    }

    boolean this_present_totnqueued = true;
    boolean that_present_totnqueued = true;
    if (this_present_totnqueued || that_present_totnqueued) {
      if (!(this_present_totnqueued && that_present_totnqueued))
        return false;
      if (this.totnqueued != that.totnqueued)
        return false;
    }

    boolean this_present_nqueued = true;
    boolean that_present_nqueued = true;
    if (this_present_nqueued || that_present_nqueued) {
      if (!(this_present_nqueued && that_present_nqueued))
        return false;
      if (this.nqueued != that.nqueued)
        return false;
    }

    boolean this_present_totwkqueued = true;
    boolean that_present_totwkqueued = true;
    if (this_present_totwkqueued || that_present_totwkqueued) {
      if (!(this_present_totwkqueued && that_present_totwkqueued))
        return false;
      if (this.totwkqueued != that.totwkqueued)
        return false;
    }

    boolean this_present_wkqueued = true;
    boolean that_present_wkqueued = true;
    if (this_present_wkqueued || that_present_wkqueued) {
      if (!(this_present_wkqueued && that_present_wkqueued))
        return false;
      if (this.wkqueued != that.wkqueued)
        return false;
    }

    boolean this_present_status = true;
    boolean that_present_status = true;
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (this.status != that.status)
        return false;
    }

    boolean this_present_svrcnt = true;
    boolean that_present_svrcnt = true;
    if (this_present_svrcnt || that_present_svrcnt) {
      if (!(this_present_svrcnt && that_present_svrcnt))
        return false;
      if (this.svrcnt != that.svrcnt)
        return false;
    }

    boolean this_present_spawn_state = true;
    boolean that_present_spawn_state = true;
    if (this_present_spawn_state || that_present_spawn_state) {
      if (!(this_present_spawn_state && that_present_spawn_state))
        return false;
      if (this.spawn_state != that.spawn_state)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(QueueState other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    QueueState typedOther = (QueueState)other;

    lastComparison = Boolean.valueOf(isSetSgid()).compareTo(typedOther.isSetSgid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSgid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sgid, typedOther.sgid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSaddr()).compareTo(typedOther.isSetSaddr());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSaddr()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.saddr, typedOther.saddr);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTotnqueued()).compareTo(typedOther.isSetTotnqueued());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotnqueued()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.totnqueued, typedOther.totnqueued);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNqueued()).compareTo(typedOther.isSetNqueued());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNqueued()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nqueued, typedOther.nqueued);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTotwkqueued()).compareTo(typedOther.isSetTotwkqueued());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotwkqueued()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.totwkqueued, typedOther.totwkqueued);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWkqueued()).compareTo(typedOther.isSetWkqueued());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWkqueued()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.wkqueued, typedOther.wkqueued);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(typedOther.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, typedOther.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSvrcnt()).compareTo(typedOther.isSetSvrcnt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSvrcnt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.svrcnt, typedOther.svrcnt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSpawn_state()).compareTo(typedOther.isSetSpawn_state());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpawn_state()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.spawn_state, typedOther.spawn_state);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueueState(");
    boolean first = true;

    sb.append("sgid:");
    sb.append(this.sgid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("saddr:");
    if (this.saddr == null) {
      sb.append("null");
    } else {
      sb.append(this.saddr);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("totnqueued:");
    sb.append(this.totnqueued);
    first = false;
    if (!first) sb.append(", ");
    sb.append("nqueued:");
    sb.append(this.nqueued);
    first = false;
    if (!first) sb.append(", ");
    sb.append("totwkqueued:");
    sb.append(this.totwkqueued);
    first = false;
    if (!first) sb.append(", ");
    sb.append("wkqueued:");
    sb.append(this.wkqueued);
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    sb.append(this.status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("svrcnt:");
    sb.append(this.svrcnt);
    first = false;
    if (!first) sb.append(", ");
    sb.append("spawn_state:");
    sb.append(this.spawn_state);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueueStateStandardSchemeFactory implements SchemeFactory {
    public QueueStateStandardScheme getScheme() {
      return new QueueStateStandardScheme();
    }
  }

  private static class QueueStateStandardScheme extends StandardScheme<QueueState> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueueState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SGID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sgid = iprot.readI64();
              struct.setSgidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SADDR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.saddr = iprot.readString();
              struct.setSaddrIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TOTNQUEUED
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.totnqueued = iprot.readI32();
              struct.setTotnqueuedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NQUEUED
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.nqueued = iprot.readI32();
              struct.setNqueuedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TOTWKQUEUED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.totwkqueued = iprot.readI64();
              struct.setTotwkqueuedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // WKQUEUED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.wkqueued = iprot.readI64();
              struct.setWkqueuedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // SVRCNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.svrcnt = iprot.readI32();
              struct.setSvrcntIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // SPAWN_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.spawn_state = iprot.readI32();
              struct.setSpawn_stateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueueState struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SGID_FIELD_DESC);
      oprot.writeI64(struct.sgid);
      oprot.writeFieldEnd();
      if (struct.saddr != null) {
        oprot.writeFieldBegin(SADDR_FIELD_DESC);
        oprot.writeString(struct.saddr);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TOTNQUEUED_FIELD_DESC);
      oprot.writeI32(struct.totnqueued);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NQUEUED_FIELD_DESC);
      oprot.writeI32(struct.nqueued);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TOTWKQUEUED_FIELD_DESC);
      oprot.writeI64(struct.totwkqueued);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(WKQUEUED_FIELD_DESC);
      oprot.writeI64(struct.wkqueued);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.status);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SVRCNT_FIELD_DESC);
      oprot.writeI32(struct.svrcnt);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SPAWN_STATE_FIELD_DESC);
      oprot.writeI32(struct.spawn_state);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueueStateTupleSchemeFactory implements SchemeFactory {
    public QueueStateTupleScheme getScheme() {
      return new QueueStateTupleScheme();
    }
  }

  private static class QueueStateTupleScheme extends TupleScheme<QueueState> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueueState struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSgid()) {
        optionals.set(0);
      }
      if (struct.isSetSaddr()) {
        optionals.set(1);
      }
      if (struct.isSetTotnqueued()) {
        optionals.set(2);
      }
      if (struct.isSetNqueued()) {
        optionals.set(3);
      }
      if (struct.isSetTotwkqueued()) {
        optionals.set(4);
      }
      if (struct.isSetWkqueued()) {
        optionals.set(5);
      }
      if (struct.isSetStatus()) {
        optionals.set(6);
      }
      if (struct.isSetSvrcnt()) {
        optionals.set(7);
      }
      if (struct.isSetSpawn_state()) {
        optionals.set(8);
      }
      oprot.writeBitSet(optionals, 9);
      if (struct.isSetSgid()) {
        oprot.writeI64(struct.sgid);
      }
      if (struct.isSetSaddr()) {
        oprot.writeString(struct.saddr);
      }
      if (struct.isSetTotnqueued()) {
        oprot.writeI32(struct.totnqueued);
      }
      if (struct.isSetNqueued()) {
        oprot.writeI32(struct.nqueued);
      }
      if (struct.isSetTotwkqueued()) {
        oprot.writeI64(struct.totwkqueued);
      }
      if (struct.isSetWkqueued()) {
        oprot.writeI64(struct.wkqueued);
      }
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.status);
      }
      if (struct.isSetSvrcnt()) {
        oprot.writeI32(struct.svrcnt);
      }
      if (struct.isSetSpawn_state()) {
        oprot.writeI32(struct.spawn_state);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueueState struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(9);
      if (incoming.get(0)) {
        struct.sgid = iprot.readI64();
        struct.setSgidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.saddr = iprot.readString();
        struct.setSaddrIsSet(true);
      }
      if (incoming.get(2)) {
        struct.totnqueued = iprot.readI32();
        struct.setTotnqueuedIsSet(true);
      }
      if (incoming.get(3)) {
        struct.nqueued = iprot.readI32();
        struct.setNqueuedIsSet(true);
      }
      if (incoming.get(4)) {
        struct.totwkqueued = iprot.readI64();
        struct.setTotwkqueuedIsSet(true);
      }
      if (incoming.get(5)) {
        struct.wkqueued = iprot.readI64();
        struct.setWkqueuedIsSet(true);
      }
      if (incoming.get(6)) {
        struct.status = iprot.readI32();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(7)) {
        struct.svrcnt = iprot.readI32();
        struct.setSvrcntIsSet(true);
      }
      if (incoming.get(8)) {
        struct.spawn_state = iprot.readI32();
        struct.setSpawn_stateIsSet(true);
      }
    }
  }

}

